{"name": "Ошибка при попытке получить список заказов неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткеполучить список заказов неавторизованным пользователем", "start": 1723885832602, "stop": 1723885832762, "uuid": "c32c0da2-0549-405a-879a-368764e4be54", "historyId": "ac9ba4c123e6a6d0430b13623b37735f", "testCaseId": "ac9ba4c123e6a6d0430b13623b37735f", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}