{"name": "Ошибка при попытке получить список заказов неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткеполучить список заказов неавторизованным пользователем", "start": 1724065594490, "stop": 1724065594657, "uuid": "d8bb92ab-6196-4832-bfba-6f32fd131e59", "historyId": "ac9ba4c123e6a6d0430b13623b37735f", "testCaseId": "ac9ba4c123e6a6d0430b13623b37735f", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "13308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}