{"name": "Изменение данных неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткиизменить данные неавторизованным пользователем", "parameters": [{"name": "data_user", "value": "'_Up3CF7k3M'"}], "start": 1723885841949, "stop": 1723885842102, "uuid": "a2d7dcaf-f565-4f17-bfc7-669b0dbe3e20", "historyId": "b531bc348156c582e4d591f1f3c64357", "testCaseId": "75e3752286952ce47f86b20de866b56d", "fullName": "tests.test_update_user_data.TestUpdateUserData#test_update_user_data_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}