{"name": "Изменение данных неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткиизменить данные неавторизованным пользователем", "parameters": [{"name": "data_user", "value": "'Y*U392aluO'"}], "start": 1724065603385, "stop": 1724065603573, "uuid": "5699c0f2-2895-4610-9e23-96c2010a3e53", "historyId": "da371ba257b4d1bd20c8f4d9bd8f19ea", "testCaseId": "75e3752286952ce47f86b20de866b56d", "fullName": "tests.test_update_user_data.TestUpdateUserData#test_update_user_data_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "13308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}