{"name": "Изменение данных неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткиизменить данные неавторизованным пользователем", "parameters": [{"name": "data_user", "value": "'Andrew'"}], "start": 1723885842110, "stop": 1723885842322, "uuid": "3e1dbf04-b0f2-4e7b-a857-7f794cb61bdd", "historyId": "a3b73dd114fa2ecbdfcece9447bcd030", "testCaseId": "75e3752286952ce47f86b20de866b56d", "fullName": "tests.test_update_user_data.TestUpdateUserData#test_update_user_data_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}